server:
  port: 8080

mybatis:
  # resources/mapper/ 에 있는 모든 xml 파일
  mapper-locations: classpath*:mapper/*.xml

spring:

  datasource:
    driver-class-name: com.sap.db.jdbc.Driver
    url: jdbc:sap://fab7ea2c-516c-465e-8207-80b56fee79ee.hana.trial-us10.hanacloud.ondemand.com:443??encrypt =true&validateCertificate=true&traceFile=stdout&traceOptions=CONNECTIONS,API,STATISTICS,CLEANERS,TIMESTAMPS,ELAPSEDTIMES
    username: DBADMIN
    password: dlwlsgh1595A

  thymeleaf:
    prefix : classpath:templates/
    suffix : .html
    cache : false


