server:
  port: 8080

mybatis:
  # resources/mapper/ 에 있는 모든 xml 파일
  mapper-locations: classpath*:mapper/*.xml

spring:
  datasource:
    driver-class-name: com.sap.db.jdbc.Driver
    url: jdbc:sap://fab7ea2c-516c-465e-8207-80b56fee79ee.hana.trial-us10.hanacloud.ondemand.com:443??encrypt =true&validateCertificate=true&traceFile=stdout&traceOptions=CONNECTIONS,API,STATISTICS,CLEANERS,TIMESTAMPS,ELAPSEDTIMES
    username: DBADMIN
    password: dlwlsgh1595A
  #mysql 커넥터
  #datasource:
  # driver-class-name: com.mysql.cj.jdbc.Driver
  # url: jdbc:mysql://127.0.0.1:3306/saptest?serverTimezone=Asia/Seoul
  # username: jinholee
  # password: dlwlsgh1595@
  thymeleaf:
    prefix : classpath:templates/
    suffix : .html
    cache : false





